# Generated by Django 6.0.3 on 2026-04-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_nombre',
            field=models.CharField(default='card1.webp', help_text='Ejemplo: card1.webp', max_length=100),
            preserve_default=False,
        ),
    ]
